---
- name: Delete instance config ports
  when: item.value.port_id is defined
  shell:
    cmd: "openstack port delete {{ item.value.port_id }}"
  loop: "{{ router.value.connections | dict2items }}"
