---
- name: Initialize empty NIC params
  set_fact:
    nic_params: ""

- name: Build NIC params from networks
  set_fact: 
    nic_params: "{{ nic_params }} --nic net-id={{ networks[item.key].id }},v4-fixed-ip=\"{{ item.value.fixed_ipv4 }}\""
  loop: "{{ instance.value.networks | dict2items }}"

- name: Add SSHJump interface
  when: instance.value.sshjumpable is true and instance.value.key_name is defined
  set_fact: 
    nic_params: "{{ nic_params }} --nic net-id={{ sshjump_net.id }}"

- name: Deploy instances
  command: >
    openstack server create
    --flavor {{ instance.value.flavor }}
    --image  {{ instance.value.image }}
    --boot-from-volume {{ instance.value.image_size }}
    {{ nic_params }}
    --key-name {{ instance.value.key_name }} 
    {{ instance.key }}
  ignore_errors: yes

- name: Pause for instance setup
  pause: 
    seconds: 30
