---
- name: Deploy instances
  command: >
    openstack server create
    --flavor {{ item.1.flavor }}
    --image  {{ item.1.image }}
    --boot-from-volume {{ item.1.image_size }}
    --nic net-id={{ item.0.net_id }},v4-fixed-ip={{ item.1.fixed_ip }}
    --key-name {{ ansible_control_key_name }} 
    {{ item.1.name }}
  ignore_errors: yes
  loop: "{{ lookup('subelements', networks, 'instances') }}"

- name: Create port to instance
  shell:
    cmd: "openstack port create --network {{ item.0.net_id }} --fixed-ip subnet={{ item.0.subnet_id }},ip-address={{ item.1.control_port_addr }} --format json {{ item.1.name }}_CONTROL_PORT"
  loop: "{{ lookup('subelements', networks, 'instances') }}"
  register: port_create_results

- name: Attach ports to instances
  shell:
    cmd: "openstack server add port {{ deploy_box_id }} {{ (port_create_results.results[current_idx].stdout | from_json).id }}"
  loop: "{{ lookup('subelements', networks, 'instances') }}"
  loop_control:
    index_var: current_idx

- name: Pause for instance setup
  pause: 
    seconds: 30
