---

#########################################################################################################################################
#                                                         P F S E N S E S                                                               #
#########################################################################################################################################

pfsenses:
  team_1_main_pfsense: {
    interfaces: {
      WAN:                  { ip: 88.31.10.1/24,  remote_networks: internet },
      REMOTE:               { ip: 10.0.1.254/24,  remote_networks: main_1_remotes },
      LAN:                  { ip: 192.168.1.1/24 }
    }
  }

  outer_1_pfsense: {
    interfaces: {
      WAN:                  { ip: 10.0.1.253/24, remote_networks: outer_1_remotes },
      LAN:                  { ip: 172.128.1.1/24 }
    }
  }

  team_2_main_pfsense: {
    interfaces: {
      WAN:                  { ip: 88.31.10.254/24, remote_networks: internet },
      REMOTE:               { ip: 10.0.2.254/24,   remote_networks: main_2_remotes },
      LAN:                  { ip: 192.168.2.1/24 }
    }
  }

  outer_2_pfsense: {
    interfaces: {
      WAN:                  { ip: 10.0.2.253/24, remote_networks: outer_2_remotes },
      LAN:                  { ip: 172.128.2.1/24 }
    }
  }


#########################################################################################################################################
#                                                             R U L E S                                                                 #
#########################################################################################################################################

rules:
  options: { log: yes }

  # CONFIG:
  #   config_from_lan:        { src: t1_remote,       dst: 10.0.1.254,        protocol: tcp,      dst_port: admin_ports }
  #   config_from_lan:        { src: t1_remote,       dst: 10.0.1.253,        protocol: tcp,      dst_port: admin_ports }
  #   config_from_lan:        { src: t2_remote,       dst: 10.0.2.254,        protocol: tcp,      dst_port: admin_ports }
  #   config_from_lan:        { src: t2_remote,       dst: 10.0.2.253,        protocol: tcp,      dst_port: admin_ports }

  ALLOW_ALL:
    allow_all:              { src: any,             dst: any,                 protocol: any }

  # ANTI_GREY_LOCKOUT:
  #   anti_base_lockout:      { src: grey_lan,             dst: any,                 protocol: any }
  #   anti_gateway_lockout:   { src: grey_gateway,         dst: any,                 protocol: any }
  #   anti_s1con_lockout:     { src: grey_s1_con,          dst: any,                 protocol: any }
  #   anti_s2con_lockout:     { src: grey_s2_con,          dst: any,                 protocol: any }
  #   anti_rcon_lockout:      { src: grey_r_con,           dst: any,                 protocol: any }

  # ICMP:
  #   allow_icmp:             { src: any,             dst: any,                 protocol: icmp,     icmptype: any, log: no }

  # BLUE_INTERFERENCE:
  #   block_blue_a:           { src: blue_1_lans,     dst: blue_2_lans,         protocol: any,      action: block}
  #   block_blue_b:           { src: blue_2_lans,     dst: blue_1_lans,         protocol: any,      action: block}

  # FROM_FARGO:
  #   config_from_fargo:      { src: fargo_station,   dst: 10.20.30.101,        protocol: tcp,      dst_port: admin_ports }
  #   ssh_from_fargo:         { src: fargo_station,   dst: paris_ssh_hosts,     protocol: tcp,      dst_port: ssh_port }
  #   proxy_from_fargo:       { src: fargo_station,   dst: paris_server,        protocol: tcp,      dst_port: squid_port }
  #   smb_from_fargo:         { src: fargo_station,   dst: paris_server,        protocol: tcp,      dst_port: smb_ports }
  #   vnc_from_fargo:         { src: fargo_station,   dst: paris_station,       protocol: tcp,      dst_port: vnc_ports }

  # TO_FARGO:
  #   ssh_from_server:        { src: paris_server,    dst: all_fargo_subnets,   protocol: tcp,      dst_port: ssh_port }
  #   dns_from_server:        { src: paris_server,    dst: fargo_ads,           protocol: tcp/udp,  dst_port: dns_port }
  #   laptop_to_fargo:        { src: paris_laptop,    dst: all_fargo_subnets,   protocol: any }


#########################################################################################################################################
#                                                           A L I A S E S                                                               #
#########################################################################################################################################

hosts_aliases:
  grey_lan:             { ip: 10.0.0.0/24 }
  grey_gateway:         { ip: 10.0.1.252 }
  grey_s1_con:          { ip: 172.128.1.250 }
  grey_s2_con:          { ip: 172.128.2.250 }
  grey_r_con:           { ip: 88.31.10.250 }

  red_lan:              { ip: 88.31.10.0/24 }

  t1_local:             { ip: 192.168.1.0/24 }
  t1_remote:            { ip: 10.0.1.0/24 }
  t1_sat:               { ip: 172.128.1.0/24 }
  blue_1_lans:          { ip: t1_local t1_remote t1_sat}
  outer_1_remotes:      { ip: t1_remote grey_lan red_lan }
  main_1_remotes:       { ip: grey_lan t1_sat }

  t2_local:             { ip: 192.168.2.0/24 }
  t2_remote:            { ip: 10.0.2.0/24 }
  t2_sat:               { ip: 172.128.2.0/24 }
  blue_2_lans:          { ip: t2_local t2_remote t2_sat}
  outer_2_remotes:      { ip: t2_remote grey_lan red_lan }
  main_2_remotes:       { ip: grey_lan t2_sat }

  internet:             { ip: 0.0.0.0/0 }


  # t2_local_remotes:     { ip: t2_remote }
  # t2_remote_remotes:    { ip: t2_local t2_sat}

  # paris_lan:            { ip: 10.20.30.0/24 }
  # paris_router:         { ip: 10.20.30.1 }
  # paris_station:        { ip: 10.20.30.2 }
  # paris_server:         { ip: 10.20.30.3 }
  # paris_laptop:         { ip: 10.20.30.4 }
  # paris_ssh_hosts:      { ip: paris_server paris_router }

  # fargo_station:        { ip: 10.100.200.10 }
  # fargo_ads:            { ip: 192.168.1.1 192.168.1.2 192.168.1.3 }

  # all_fargo_subnets:    { ip: 192.168.0.0/16 10.0.0.0/8 172.16.0.0/16 }
  # ipsec_vtis:           { ip: 10.9.8.1 10.9.8.2 }

ports_aliases:
  admin_ports:          { port: 22 80 443 }
  dns_port:             { port: 53 }
  rdp_port:             { port: 3389 }
  ssh_port:             { port: 22 }
  smb_ports:            { port: 135 137 139 445 }
  vnc_ports:            { port: 5900-5901 }