---

#########################################################################################################################################
#                                                         P F S E N S E S                                                               #
#########################################################################################################################################

pfsenses:
  team_1_main_pfsense: {
    interfaces: {
      WAN:                { ip: 10.0.1.254/24 },
      LAN:                { ip: 192.168.1.1/24 }
    }
  }

  # outer_1_pfsense: {
  #   interfaces: {
  #     WAN:                  { ip: 10.0.1.253/24 },
  #     LAN:                  { ip: 172.128.1.1/24 }
  #   }
  # }

  # team_2_main_pfsense: {
  #   interfaces: {
  #     WAN:                  { ip: 10.0.2.254/24 },
  #     LAN:                  { ip: 192.168.2.1/24 }
  #   }
  # }

  # outer_2_pfsense: {
  #   interfaces: {
  #     WAN:                  { ip: 10.0.2.253/24 },
  #     LAN:                  { ip: 172.128.2.1/24 }
  #   }
  # }

  # link_pfsense: {
  #   interfaces: {
  #     WAN:                  { ip: 88.31.10.1/24 },
  #     LAN:                  { ip: 10.0.1.252/24 },
  #     OPT1:                 { ip: 10.0.2.252/24 }
  #     }
  #   }


#########################################################################################################################################
#                                                             R U L E S                                                                 #
#########################################################################################################################################

rules:
  options: { log: yes }

  # CONFIG:
  #   config_from_lan:        { src: paris_lan,       dst: 10.20.30.101,        protocol: tcp,      dst_port: admin_ports }

  ALLOW_ALL:
    allow_all:              { src: any,             dst: any,                 protocol: any,      action: pass }

  # ANTI_LOCKOUT:
  #   anti_lockout:           { src: any,             dst: any,                 protocol: tcp,      dst_port: admin_ports }

  # ICMP:
  #   block_redirects:        { src: any,             dst: any,                 protocol: icmp,     icmptype: redir, action: block, log: yes }
  #   allow_icmp:             { src: any,             dst: any,                 protocol: icmp,     icmptype: any, log: no }

  # OSPF:
  #   ospf_vtis:              { src: ipsec_vtis,      dst: ipsec_vtis,          protocol: ospf,     log: no }

  # FROM_FARGO:
  #   config_from_fargo:      { src: fargo_station,   dst: 10.20.30.101,        protocol: tcp,      dst_port: admin_ports }
  #   ssh_from_fargo:         { src: fargo_station,   dst: paris_ssh_hosts,     protocol: tcp,      dst_port: ssh_port }
  #   proxy_from_fargo:       { src: fargo_station,   dst: paris_server,        protocol: tcp,      dst_port: squid_port }
  #   smb_from_fargo:         { src: fargo_station,   dst: paris_server,        protocol: tcp,      dst_port: smb_ports }
  #   vnc_from_fargo:         { src: fargo_station,   dst: paris_station,       protocol: tcp,      dst_port: vnc_ports }

  # TO_FARGO:
  #   ssh_from_server:        { src: paris_server,    dst: all_fargo_subnets,   protocol: tcp,      dst_port: ssh_port }
  #   dns_from_server:        { src: paris_server,    dst: fargo_ads,           protocol: tcp/udp,  dst_port: dns_port }
  #   laptop_to_fargo:        { src: paris_laptop,    dst: all_fargo_subnets,   protocol: any }


#########################################################################################################################################
#                                                           A L I A S E S                                                               #
#########################################################################################################################################

hosts_aliases:
  # red:                  { ip: 88.31.10.0/24 }
  # red_r1_w:             { ip: 88.31.10.1 }

  # t1_local:             { ip: 192.168.1.0/24 }
  # t1_local_r1_r:        { ip: 192.168.1.1 }

  # t1_remote:            { ip: 10.0.1.0/24 }
  # t1_remote_r1_l:       { ip: 10.0.1.254 }
  # t1_remote_r2_s:       { ip: 10.0.1.253 }
  # t1_remote_r3_r:       { ip: 10.0.1.252 }

  # t1_sat:               { ip: 172.128.1.0/24 }
  # t1_sat_r1_r:          { ip: 172.128.1.1 }

  # t2_local:             { ip: 192.168.2.0/24 }
  # t2_local_r1_r:        { ip: 192.168.2.1 }

  # t2_remote:            { ip: 10.0.2.0/24 }
  # t2_remote_r1_l:       { ip: 10.0.2.254 }
  # t2_remote_r2_s:       { ip: 10.0.2.253 }
  # t2_remote_r3_r:       { ip: 10.0.2.252 }

  # t2_sat:               { ip: 172.128.2.0/24 }
  # t2_sat_r1_r:          { ip: 172.128.2.1 }

  internet:             { ip: 0.0.0.0/0 }

  # paris_lan:            { ip: 10.20.30.0/24 }
  # paris_router:         { ip: 10.20.30.1 }
  # paris_station:        { ip: 10.20.30.2 }
  # paris_server:         { ip: 10.20.30.3 }
  # paris_laptop:         { ip: 10.20.30.4 }
  # paris_ssh_hosts:      { ip: paris_server paris_router }

  # fargo_station:        { ip: 10.100.200.10 }
  # fargo_ads:            { ip: 192.168.1.1 192.168.1.2 192.168.1.3 }

  # all_fargo_subnets:    { ip: 192.168.0.0/16 10.0.0.0/8 172.16.0.0/16 }
  # ipsec_vtis:           { ip: 10.9.8.1 10.9.8.2 }

ports_aliases:
  admin_ports:          { port: 22 80 443 }
  # dns_port:             { port: 53 }
  # rdp_port:             { port: 3389 }
  # ssh_port:             { port: 22 }
  # smb_ports:            { port: 135 137 139 445 }
  # vnc_ports:            { port: 5900-5901 }