---
- name: "Create Network - {{ network.key }}_net"
  os_network:
    name: "{{ network.key }}_net"
    state: present
    port_security_enabled: "{{ network.value.port_security_enabled }}"
  register: net_create_result

- name: Register Net ID
  set_fact: 
    networks: "{{ networks | combine({ network.key: { 'id': net_create_result.id }}, recursive=true) }}"

- name: "Create Subnet - {{ network.key }}_subnet"
  when: network.value.host_routes is not defined
  os_subnet:
    state: present
    network_name: "{{ network.key }}_net"
    name: "{{ network.key }}_subnet"
    cidr: "{{ network.value.subnet.address }}"
    gateway_ip: "{{ network.value.subnet.gateway_ip }}"
  register: subnet_create_result_wroutes

- name: "Create Subnet - {{ network.key }}_subnet"
  when: network.value.host_routes is defined
  os_subnet:
    state: present
    network_name: "{{ network.key }}_net"
    name: "{{ network.key }}_subnet"
    cidr: "{{ network.value.subnet.address }}"
    gateway_ip: "{{ network.value.subnet.gateway_ip }}"
    host_routes: "{{ network.value.host_routes }}"
  register: subnet_create_result_woroutes

- name: Register Subnet ID
  when: network.value.host_routes is not defined
  set_fact: 
    networks: "{{ networks | combine({ network.key: { 'subnet': { 'id': subnet_create_result_wroutes.id }}}, recursive=true) }}"

- name: Register Subnet ID
  when: network.value.host_routes is defined
  set_fact: 
    networks: "{{ networks | combine({ network.key: { 'subnet': { 'id': subnet_create_result_woroutes.id }}}, recursive=true) }}"

- name: Deploy instances on network
  when: network.value.instances is defined
  # os_server:
  #   flavor: "{{ instance.value.flavor }}"
  #   image: "{{ instance.value.image }}"
  #   key_name: "{{ instance.value.key_name }}"
  #   boot_from_volume: true
  #   volume_size: "{{ instance.value.image_size }}"
  #   name: "{{ instance.key }}"
  #   nics: "net-id={{ networks[network.key].id }},v4-fixed-ip=\"{{ instance.value.fixed_ipv4 }}\""
  #   terminate_volume: true
  command: >
    openstack server create
    --flavor {{ instance.value.flavor }}
    --image  {{ instance.value.image }}
    --boot-from-volume {{ instance.value.image_size }}
    --nic net-id={{ networks[network.key].id }},v4-fixed-ip="{{ instance.value.fixed_ipv4 }}"
    --key-name {{ instance.value.key_name }} 
    {{ instance.key }}
    --wait
  ignore_errors: yes
  loop: "{{ network.value.instances | dict2items }}"
  loop_control:
    loop_var: instance
