---
- name: Deploy networks
  hosts: localhost
  environment:
    ANSIBLE_HOST_KEY_CHECKING: "False"
  vars:
    deploy_box_id: "53954658-1ee8-4de9-b768-cf40e91cc536"
    default_key_name: remote
    ansible_control_key_name: netDeploy
    pfsense:
      name: "BLUE_{{ team_number }}_PFSENSE"
      image: PFsense-2.6.0-Cloudinit
      image_size: 60
      flavor: large
    networks:
      0:
        name: LOCAL_{{ team_number }}_NET
        subnet_name: LOCAL_{{ team_number }}_SUBNET
        subnet_addr: 10.0.1.0/24
        gateway_addr: 10.0.1.254
        port_security_enabled: false
        internet: false
        instances:
          - name: LOCAL_{{ team_number }}_TEST1
            os_type: linux
            flavor: small
            image: UbuntuJammy2204-Desktop
            image_size: 40
            fixed_ip: 10.0.1.10
            control_port_addr: 10.0.1.253
          - name: LOCAL_{{ team_number }}_TEST2
            os_type: linux
            flavor: small
            image: UbuntuJammy2204-Desktop
            image_size: 40
            fixed_ip: 10.0.1.11
            control_port_addr: 10.0.1.252
      1:
        name: REMOTE_{{ team_number }}_NET
        subnet_name: REMOTE_{{ team_number }}_SUBNET
        subnet_addr: 10.0.2.0/24
        gateway_addr: 10.0.2.254
        port_security_enabled: false
        internet: false
        instances:
          - name: REMOTE_{{ team_number }}_TEST1
            flavor: small
            image: UbuntuJammy2204-Desktop
            image_size: 40
            fixed_ip: 10.0.2.10
            control_port_addr: 10.0.2.253
          - name: REMOTE_{{ team_number }}_TEST2
            flavor: small
            image: UbuntuJammy2204-Desktop
            image_size: 40
            fixed_ip: 10.0.2.11
            control_port_addr: 10.0.2.252

  tasks:
    - include_tasks: ./deploy_networks/tasks/main.yml
    - include_tasks: ./deploy_pfsense/tasks/main.yml
    - include_tasks: ./deploy_instances/tasks/main.yml
    - include_tasks: ./add_internet_to_wan/tasks/main.yml

- name: Configure linux instances
  hosts: linux
  tasks:
    - include_tasks: ./setup_linux_instances/tasks/main.yml

# - name: Configure windows instances
#   hosts: linux
#   tasks:
#     - include_tasks: ./setup_windows_instances/tasks/main.yml

- name: Cleanup
  hosts: localhost
  tasks:
    - include_tasks: ./cleanup/tasks/main.yml