---
- name: Config pfSense Gateway
  pfsensible.core.pfsense_gateway:
    name: "{{ gateway.key }}"
    gateway: "{{ gateway.value.gateway }}"
    interface: "{{ gateway.value.iface }}"
    ipprotocol: inet # inet=ipv4, inetv6=ipv6
  loop: "{{ router.value.gateways | dict2items }}"
  loop_control:
    loop_var: gateway
    label: "{{ gateway.key }}"

- name: Config Default Gateway
  when: gateway.value.is_default is defined and gateway.value.is_default == true
  pfsensible.core.pfsense_default_gateway:
    gateway: "{{ gateway.key }}"
    ipprotocol: inet # inet=ipv4, inetv6=ipv6
  loop: "{{ router.value.gateways | dict2items }}"
  loop_control:
    loop_var: gateway
    label: "{{ gateway.key }}"

- name: Assign Gateway to Interface
  when: interface.value.ipv4_gateway is defined
  pfsensible.core.pfsense_interface:
    descr: "{{ interface.key }}"
    interface: "{{ interface.value.iface }}"
    ipv4_type: "{{ interface.value.ipv4_type }}"
    ipv4_address: "{{ interface.value.ipv4 }}"
    ipv4_prefixlen: "{{ interface.value.cidr }}"
    ipv4_gateway: "{{ interface.value.ipv4_gateway }}"
    enable: true
  loop: "{{ router.value.interfaces | dict2items }}"
  loop_control:
    loop_var: interface
  register: results

- name: debug assignment
  debug:
    msg: "{{ results }}"